title: XR, HRI & Robotics Deadlines
description: Countdowns to major XR, human–robot interaction and robotics conference deadlines
author: Tony Le

url: 'https://tonydle.github.io'
domain: 'tonydle.github.io'
baseurl: '/hri-deadlines'

twitter_hashtag: robotics-deadlines
github_username: tonydle
github_repo: hri-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
